### ISSUE TITLE
Obtaining error while launching VTune Profile in ubuntu on VSCode

### ISSUE THREAD

**Issue by TryerGit** [intel/vscode-oneapi-analysis-configurator#15]
Hello,

On launching the application from within VSCode on a C++ project, I obtain the following error:

[18316:0122/172321.029351:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018
[18316:0122/172321.031106:ERROR:cert_verify_proc_builtin.cc(690)] CertVerifyProcBuiltin for 127.0.0.1 failed:
----- Certificate i=0 (CN=TryerGit-Inspiron-3268) -----
ERROR: No matching issuer found

Could you please help fix this error? If you need more information, please let me know.

Thank you.

**Comment by amakarev** [comment]
@TryerGit Hello. 
I believe that the problem is not with the VScode extension but with the Vtune Profiler. Could you please describe your problem here? https://community.intel.com/t5/Analyzers/bd-p/analyzers

**Comment by amakarev** [comment]
@TryerGit Hello.
 Can you provide more details about your environment? 
Please provide operating system version, oneapi base toolkit version and NSS library version

**Comment by TryerGit** [comment]
Hello,
My OS version is:

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

```
oneapi base toolkit version is:

Note sure how to find this but on opening VTune Profiler, I obtain :

```
2023.0.0
Product build: 624757
Installation directory: /opt/intel/oneapi/vtune/2023.0.0

```
Regarding NSS library version, I am unsure how to find this. Could you let me know the command to get this information?
----
The steps that lead to this error are:
I compile/build a C++ project using make. This produces an executable in .vscode/dist/Release/GNU-Linux/ folder (as this is what my makefile asks the build process to do.)

After successful completion, from within VSCode, I issue the command "Intel oneAPI: Launch VTune Profiler".

This opens up a dialog box in VSCode with

"You can choose the executable file or change the settings by yourself."

The just recently built file is already chosen by default:

".vscode/dist/Release/GNU-Linux/linux"

On going ahead with this choice, VSCode executes the ./launch-vtune.sh file

The contents of this file (which seems to be generated directly by the extension (?) are:

```
#!/bin/bash
source "/opt/intel/oneapi/vtune/latest/env/vars.sh" && vtune-gui --project-path "/home/TryerGit/Project/vtune" --app-path "/home/TryerGit/project/.vscode/dist/Release/GNU-Linux/linux"
```
This then leads to the error reported in the OP.

Thank you.

**Comment by amakarev** [comment]
@TryerGit Sorry for such a long answer. 
Are you using a local machine or are you connecting via vscode remote SSH to a remote one?
One of the optional pre-requisites is the nss library.
Please check with the following command and attach its output: apt list --installed | grep nss

**Comment by TryerGit** [comment]
Hello,

The output of `apt list --installed | grep nss` is:

```
:~$ apt list --installed | grep nss

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libevent-openssl-2.1-7/focal,now 2.1.11-stable-1 amd64 [installed,automatic]
libjansson4/focal,now 2.12-1build1 amd64 [installed,automatic]
libnss-mdns/focal,now 0.14.1-1ubuntu1 amd64 [installed,automatic]
libnss-systemd/focal-updates,now 245.4-4ubuntu3.19 amd64 [installed,automatic]
libnss3/focal-updates,focal-security,now 2:3.49.1-1ubuntu1.8 amd64 [installed,automatic]
libxmlsec1-nss/focal,now 1.2.28-2 amd64 [installed,automatic]
openssh-client/focal-updates,now 1:8.2p1-4ubuntu0.5 amd64 [installed,automatic]
openssl/focal-updates,focal-security,now 1.1.1f-1ubuntu2.17 amd64 [installed]
perl-openssl-defaults/focal,now 4 amd64 [installed,automatic]
```

The output of running `vtune-self-checker.sh` is:
```

Intel(R) VTune(TM) Profiler Self Check Utility
Copyright (C) 2009 Intel Corporation. All rights reserved.
Build Number: 624757

HW event-based analysis (counting mode) (Intel driver)   
Example of analysis types: Performance Snapshot
    Collection: Ok
    Finalization: Ok...
    Report: Ok

Instrumentation based analysis check   
Example of analysis types: Hotspots and Threading with user-mode sampling
    Collection: Ok
    Finalization: Ok...
    Report: Ok

HW event-based analysis check (Intel driver)   
Example of analysis types: Hotspots with HW event-based sampling, HPC Performance Characterization, etc.
    Collection: Ok
vtune: Warning: To enable hardware event-based sampling, VTune Profiler has disabled the NMI watchdog timer. The watchdog timer will be re-enabled after collection completes.
    Finalization: Ok...
vtune: Warning: Cannot locate debugging information for the Linux kernel. Source-level analysis will not be possible. Function-level analysis will be limited to kernel symbol tables. See the Enabling Linux Kernel Analysis topic in the product online help for instructions.

    Report: Ok

HW event-based analysis check (Intel driver)   
Example of analysis types: Microarchitecture Exploration
    Collection: Ok
vtune: Warning: To enable hardware event-based sampling, VTune Profiler has disabled the NMI watchdog timer. The watchdog timer will be re-enabled after collection completes.
    Finalization: Ok...
vtune: Warning: Cannot locate debugging information for the Linux kernel. Source-level analysis will not be possible. Function-level analysis will be limited to kernel symbol tables. See the Enabling Linux Kernel Analysis topic in the product online help for instructions.

    Report: Ok

HW event-based analysis with uncore events (Intel driver)   
Example of analysis types: Memory Access
    Collection: Ok
vtune: Warning: To enable hardware event-based sampling, VTune Profiler has disabled the NMI watchdog timer. The watchdog timer will be re-enabled after collection completes.
    Finalization: Ok...
vtune: Warning: Cannot locate debugging information for the Linux kernel. Source-level analysis will not be possible. Function-level analysis will be limited to kernel symbol tables. See the Enabling Linux Kernel Analysis topic in the product online help for instructions.

    Report: Ok

HW event-based analysis with stacks (Perf)   
Example of analysis types: Hotspots with HW event-based sampling and call stacks
    Collection: Ok
vtune: Warning: To profile kernel modules during the session, make sure they are available in the /lib/modules/kernel_version/ location.
    Finalization: Ok...
vtune: Warning: Cannot locate debugging information for the Linux kernel. Source-level analysis will not be possible. Function-level analysis will be limited to kernel symbol tables. See the Enabling Linux Kernel Analysis topic in the product online help for instructions.

    Report: Ok

HW event-based analysis with context switches (Intel driver)   
Example of analysis types: Threading with HW event-based sampling
    Collection: Ok
vtune: Warning: To enable hardware event-based sampling, VTune Profiler has disabled the NMI watchdog timer. The watchdog timer will be re-enabled after collection completes.
    Finalization: Ok...
vtune: Warning: Cannot locate debugging information for the Linux kernel. Source-level analysis will not be possible. Function-level analysis will be limited to kernel symbol tables. See the Enabling Linux Kernel Analysis topic in the product online help for instructions.

    Report: Ok

Checking DPC++ application as prerequisite for GPU analyses: Fail
Unable to run DPC++ application on GPU connected to this system. If you are using an Intel GPU and want to verify profiling support for DPC++ applications, check these requirements:
* Install Intel(R) GPU driver.
* Install Intel(R) Level Zero GPU runtime.
* Install Intel(R) oneAPI DPC++ Runtime and set the environment.

The system is ready to be used for performance analysis with Intel VTune Profiler.
Review warnings in the output above to find product limitations, if any.

The system is ready for the following analyses:
* Performance Snapshot
* Hotspots and Threading with user-mode sampling
* Hotspots with HW event-based sampling, HPC Performance Characterization, etc.
* Microarchitecture Exploration
* Memory Access
* Hotspots with HW event-based sampling and call stacks
* Threading with HW event-based sampling

The following analyses have failed on the system:
* GPU Compute/Media Hotspots (characterization mode)
* GPU Compute/Media Hotspots (source analysis mode)

Log location: /tmp/vtune-tmp-root/self-checker-2023.02.15_09.52.28/log.txt
```

**Comment by amakarev** [comment]
@TryerGit Just to clarify, the problem is that Vtune does not start after the command "Intel oneAPI: Launch VTune Profiler"? Or it starts but with the errors that you mentioned above?

**Comment by TryerGit** [comment]
@amakarev The error continues to show and VTune does "start" in the sense that it opens up as a separate application on my machine. However, when I try, say, Performance Snapshot -> Hotspots, the option to start/run is greyed out with the following message:

`Cannot start data collection because the scope of ptrace system call is limited. To enable profiling, please set /proc/sys/kernel/yama/ptrace_scope to 0. To make this change permanent, set kernel.yama.ptrace_scope to 0 in /etc/sysctl.d/10-ptrace.conf and reboot the machine.`

This was going to be a subsequent question I would have raised in the appropriate forums as I was under the impression that the starting error mentioned in the OP is causing this inability for doing hotspot analysis and fixing the starting error would automatically lead to me being able to do hotspots analysis, etc.

**Comment by amakarev** [comment]
@TryerGit 
Since the purpose of the extension is to launch Vtune, and it is able to run it, this is not a problem with the Vscode extension, as long as it does its job. Your problem is more about configuring your system for VTune to work correctly. By the way, the error that you mentioned above is most likely not related to the inability to produce a Performance snapshot. 
For further assistance please refer to the forum I mentioned  [above](https://community.intel.com/t5/Analyzers/bd-p/analyzers)

Sorry I couldn't help you here.

**Comment by TryerGit** [comment]
@amakarev Do you know if on linux/ubuntu, on performance analyzing a built executable using VTune, one should expect the executable to open in a separate terminal? The reason why I ask is that I am having a situation where on Windows, VTune does indeed open up a separate console on which the executable runs and even if I close down this console, VTune gives me performance analysis based on how much the executable has run thus far when I closed the console.

On linux/ubuntu, I am having a tough time figuring out where exactly the executable runs at all when I start perfomance profiling using VTune. 

I have posed this question over at the forum you indicated as well -- VTune integration with Visual Studio IDE on Windows seems to run a lot easier without any warnings/errors out of the box.
